In [1]:
import pandas as pd
import numpy as np
import random as rnd

In [2]:
train_df = pd.read_csv('data/house3/ko/Auction_master_train.csv',encoding='utf-8')
test_df = pd.read_csv('data/house3/ko/Auction_master_test.csv',encoding='utf-8')
train_df.head()

,Auction_key,Auction_class,Bid_class,Claim_price,Appraisal_company,Appraisal_date,Auction_count,Auction_miscarriage_count,Total_land_gross_area,Total_land_real_area,...,Specific,Share_auction_YorN,road_name,road_bunji1,road_bunji2,Close_date,Close_result,point.y,point.x,Hammer_price
0,2687,임의,개별,1766037301,정명감정,2017-07-26 00:00:00,2,1,12592.0,37.35,...,NaN,N,해운대해변로,30.0,NaN,2018-06-14 00:00:00,배당,35.162717,129.137048,760000000
1,2577,임의,일반,152946867,희감정,2016-09-12 00:00:00,2,1,42478.1,18.76,...,NaN,N,마린시티2로,33.0,NaN,2017-03-30 00:00:00,배당,35.156633,129.145068,971889999
2,2197,임의,개별,11326510,혜림감정,2016-11-22 00:00:00,3,2,149683.1,71.00,...,NaN,N,모라로110번길,88.0,NaN,2017-12-13 00:00:00,배당,35.184601,128.996765,93399999
3,2642,임의,일반,183581724,신라감정,2016-12-13 00:00:00,2,1,24405.0,32.98,...,NaN,N,황령대로319번가길,110.0,NaN,2017-12-27 00:00:00,배당,35.154180,129.089081,256899000
4,1958,강제,일반,45887671,나라감정,2016-03-07 00:00:00,2,1,774.0,45.18,...,NaN,N,오작로,51.0,NaN,2016-10-04 00:00:00,배당,35.099630,128.998874,158660000

## (가) 모델이 회귀인지 분류인지 확인하고 머신러닝 기법을 적용

이 데이터는 회귀를 사용해야한다

# 결측치 제거

In [3]:
train_df.isnull().sum()

Auction_key                       0
Auction_class                     0
Bid_class                         0
Claim_price                       0
Appraisal_company                 0
Appraisal_date                    0
Auction_count                     0
Auction_miscarriage_count         0
Total_land_gross_area             0
Total_land_real_area              0
Total_land_auction_area           0
Total_building_area               0
Total_building_auction_area       0
Total_appraisal_price             0
Minimum_sales_price               0
First_auction_date                0
Final_auction_date                0
Final_result                      0
Creditor                          0
addr_do                           0
addr_si                           0
addr_dong                         0
addr_li                        1910
addr_san                          0
addr_bunji1                       4
addr_bunji2                    1044
addr_etc                          0
Apartment_usage                   0
Preserve_regist_date              0
Total_floor                       0
Current_floor                     0
Specific                       1869
Share_auction_YorN                0
road_name                         0
road_bunji1                      24
road_bunji2                    1778
Close_date                        0
Close_result                      0
point.y                           0
point.x                           0
Hammer_price                      0
dtype: int64

In [3]:
train1 = train_df.drop(['addr_li','addr_bunji1','addr_bunji2','Specific','road_bunji1','road_bunji2','Preserve_regist_date','Close_date','addr_etc','road_name','Appraisal_date','First_auction_date','Final_auction_date'],axis=1)
train1.isnull().sum()

Auction_key                    0
Auction_class                  0
Bid_class                      0
Claim_price                    0
Appraisal_company              0
Auction_count                  0
Auction_miscarriage_count      0
Total_land_gross_area          0
Total_land_real_area           0
Total_land_auction_area        0
Total_building_area            0
Total_building_auction_area    0
Total_appraisal_price          0
Minimum_sales_price            0
Final_result                   0
Creditor                       0
addr_do                        0
addr_si                        0
addr_dong                      0
addr_san                       0
Apartment_usage                0
Total_floor                    0
Current_floor                  0
Share_auction_YorN             0
Close_result                   0
point.y                        0
point.x                        0
Hammer_price                   0
dtype: int64

# 데이터 전처리

In [4]:
obj_df = train1.select_dtypes(include=['object']).copy()
obj_df.columns 
train1 = pd.concat([train1, pd.get_dummies(obj_df)], axis=1)
train1 = train1.drop(['Auction_class', 'Bid_class', 'Appraisal_company', 'Final_result','Creditor', 'addr_do', 'addr_si', 'addr_dong', 'addr_san','Apartment_usage', 'Share_auction_YorN', 'Close_result'], axis=1)

In [9]:
pd.get_dummies(obj_df)

,Auction_class_강제,Auction_class_임의,Bid_class_개별,Bid_class_일괄,Bid_class_일반,Appraisal_company_(주)티앤비감정,Appraisal_company_AYR감정,Appraisal_company_BNK감정,Appraisal_company_CS감정,Appraisal_company_Capital감정,...,addr_dong_휘경동,addr_dong_흑석동,addr_san_N,addr_san_Y,Apartment_usage_아파트,Apartment_usage_주상복합,Share_auction_YorN_N,Share_auction_YorN_Y,Close_result_,Close_result_배당
0,0,1,1,0,0,0,0,0,0,0,...,0,0,1,0,0,1,1,0,0,1
1,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
2,0,1,1,0,0,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
3,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
4,1,0,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
5,1,0,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
6,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
7,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
8,1,0,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
9,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
10,0,1,1,0,0,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
11,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
12,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,1
13,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
14,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
15,1,0,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
16,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
17,0,1,1,0,0,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
18,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
19,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,0,1,1,0,0,1
20,1,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,1,1,0,0,1
21,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,1
22,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
23,1,0,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
24,1,0,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
25,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,0,1,1,0,0,1
26,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
27,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
28,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
29,1,0,1,0,0,0,0,0,0,0,...,0,0,1,0,0,1,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1903,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
1904,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
1905,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
1906,1,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,1,0,1,0,1
1907,1,0,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,1
1908,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
1909,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
1910,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
1911,1,0,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,1
1912,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
1913,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
1914,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
1915,1,0,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,1
1916,1,0,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
1917,0,1,1,0,0,0,0,0,0,0,...,0,0,0,1,1,0,1,0,0,1
1918,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
1919,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
1920,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
1921,1,0,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
1922,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
1923,1,0,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
1924,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,1,0
1925,1,0,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,1
1926,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
1927,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
1928,1,0,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
1929,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
1930,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,0,1,1,0,0,1
1931,1,0,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1
1932,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,1

In [15]:
train1['a'] = train1.Hammer_price - train1.Minimum_sales_price
train1['a']

0        91200000
1       113489999
2        17239999
3        26179000
4        22660000
5        29389000
6        15180000
7       106699999
8         2180000
9        46670000
10         800001
11       28217200
12        5648000
13       70800000
14        1190000
15       47900000
16       38399000
17        5000000
18        7451100
19        1899900
20         119000
21        9899000
22       20630000
23       80400000
24        1200000
25       17131000
26       62750000
27       20111110
28       59325000
29        9512000
          ...
1903     34354999
1904     13800000
1905    325699900
1906     21060000
1907      5820000
1908    110000000
1909     66530000
1910     21800000
1911     16100000
1912    168500000
1913     68266000
1914    145615000
1915      5600000
1916     25620000
1917     11699000
1918     30000000
1919     21700000
1920     41180000
1921     76100000
1922      2100000
1923     30015000
1924     14616100
1925      2755000
1926     94788000
1927     31899500
1928      1500000
1929     67034600
1930     90999990
1931     77400000
1932     86010000
Name: a, Length: 1933, dtype: int64

In [7]:
train.isnull().sum()

Auction_key                    0
Claim_price                    0
Appraisal_date                 0
Auction_count                  0
Auction_miscarriage_count      0
Total_land_gross_area          0
Total_land_real_area           0
Total_land_auction_area        0
Total_building_area            0
Total_building_auction_area    0
Total_appraisal_price          0
Minimum_sales_price            0
First_auction_date             0
Final_auction_date             0
Total_floor                    0
Current_floor                  0
point.y                        0
point.x                        0
Hammer_price                   0
Auction_class_강제               0
Auction_class_임의               0
Bid_class_개별                   0
Bid_class_일괄                   0
Bid_class_일반                   0
Appraisal_company_(주)티앤비감정     0
Appraisal_company_AYR감정        0
Appraisal_company_BNK감정        0
Appraisal_company_CS감정         0
Appraisal_company_Capital감정    0
Appraisal_company_FACAI감정      0
                              ..
addr_dong_하단동                  0
addr_dong_하왕십리동                0
addr_dong_하월곡동                 0
addr_dong_하중동                  0
addr_dong_학장동                  0
addr_dong_한강로3가                0
addr_dong_한남동                  0
addr_dong_행당동                  0
addr_dong_현석동                  0
addr_dong_현저동                  0
addr_dong_홍은동                  0
addr_dong_홍익동                  0
addr_dong_홍제동                  0
addr_dong_화곡동                  0
addr_dong_화명동                  0
addr_dong_황학동                  0
addr_dong_회기동                  0
addr_dong_회현동1가                0
addr_dong_회현동2가                0
addr_dong_효창동                  0
addr_dong_휘경동                  0
addr_dong_흑석동                  0
addr_san_N                     0
addr_san_Y                     0
Apartment_usage_아파트            0
Apartment_usage_주상복합           0
Share_auction_YorN_N           0
Share_auction_YorN_Y           0
Close_result_                  0
Close_result_배당                0
Length: 1045, dtype: int64

In [39]:
print(train_df['Auction_class'].value_counts())
print(train_df['Bid_class'].value_counts())
print(train_df['Appraisal_company'].value_counts())
print(train_df['Final_result'].value_counts())
print(train_df['Creditor'].value_counts())
print(train_df['addr_do'].value_counts())
print(train_df['addr_si'].value_counts())
print(train_df['addr_dong'].value_counts())
print(train_df['addr_san'].value_counts())
print(train_df['Apartment_usage'].value_counts())
print(train_df['Share_auction_YorN'].value_counts())
print(train_df['Close_result'].value_counts())

임의    1439
강제     494
Name: Auction_class, dtype: int64
일반    1796
개별     125
일괄      12
Name: Bid_class, dtype: int64
자연감정        33
부경감정        33
서초감정        31
대일감정        30
삼창감정        30
한마음감정       30
프라임감정       28
대한감정        28
삼일감정        26
미르감정        23
한라감정        22
통일감정        21
대화감정        21
오상호감정       21
생림감정        20
한신감정        20
문일감정        20
내외감정        19
명장감정        19
평진감정        19
삼보감정        19
혜림감정        18
연산감정        17
가람감정        17
금정감정        17
명신감정        17
혜인감정        16
나라감정        16
가화감정        16
드림감정        15
            ..
메이트플러스감정     2
정평감정         2
유일감정         2
이앤공감감정       2
(주)티앤비감정     1
대상감정         1
현대기엄감정       1
온날감정         1
TNB감정        1
대건감정         1
심상감정         1
신화감정         1
이근태감정        1
정용규감정        1
서현감정         1
컬림비아감정       1
세라감정         1
경서감정         1
올감정          1
YM감정         1
남강감정         1
HS감정         1
서울감정         1
고기옥감정        1
에프엠지감정       1
상감감정         1
두요감정         1
한국기업가치감정     1
녹원감정         1
미소감정         1
Name: Appraisal_company, Length: 238, dtype: int64
낙찰    1933
Name: Final_result, dtype: int64
Private       483
국민은행          119
우리은행           96
중소기업은행         95
하나은행           66
신한은행           58
부산은행           50
한국주택금융공사       42
신용보증기금         39
현대캐피탈          32
서울보증보험         28
농협은행           25
SC은행           15
오에스비저축은행       14
고려저축은행         14
기술신용보증기금       12
신한카드           11
현대라이프생명보험      11
대구은행           11
흥국생명보험         10
수협중앙            9
한국씨티은행          8
성남중앙신협          8
동부화재해상보험        7
국제저축은행          6
진주저축은행          6
경남은행            6
HK저축은행          6
현대저축은행          6
세종상호저축은행        6
             ...
코오롱글로벌          1
벨류대부모기지         1
강서농협            1
대부F&D           1
지비자산관리          1
경산신협            1
광명농협            1
보은자연농산          1
수영중앙(새)         1
제3.4구잠수기수협      1
서울시도시철도공사       1
청룡동(새)          1
괴정4동(새)         1
위니더스            1
구서2동(새)         1
청도일성(새)         1
JT캐피탈           1
주택도시보증공사        1
이씨에이시스템         1
우리기술            1
마산시농협           1
KCC건설           1
서동(새)           1
감천1동(새)         1
금정기업(주)         1
남동농협            1
신길6동(새)         1
IBK저축은행         1
의령농협            1
산림조합중앙회         1
Name: Creditor, Length: 448, dtype: int64
서울    1242
부산     691
Name: addr_do, dtype: int64
노원구     129
강남구     102
사하구      96
해운대구     89
부산진구     84
강서구      78
서초구      73
마포구      71
도봉구      68
양천구      68
송파구      60
사상구      58
구로구      57
남구       56
은평구      53
북구       53
동대문구     53
동래구      51
영등포구     47
성북구      45
관악구      43
강동구      39
서대문구     37
중랑구      37
동작구      37
수영구      33
연제구      31
중구       30
영도구      29
성동구      29
금정구      29
용산구      27
금천구      25
기장군      23
광진구      23
강북구      21
종로구      17
서구       17
동구       15
Name: addr_si, dtype: int64
상계동       52
서초동       32
아현동       32
화곡동       30
신정동       30
중계동       29
재송동       27
창동        26
구로동       26
용호동       25
도곡동       23
다대동       23
목동        23
연산동       22
방학동       22
화명동       22
신림동       21
공릉동       21
봉천동       19
온천동       17
낙민동       17
주례동       17
괴정동       17
월계동       17
장림동       17
시흥동       16
방배동       16
장안동       16
전포동       16
학장동       15
          ..
가산동        1
토성동5가      1
수색동        1
청암동        1
연남동        1
노고산동       1
보수동2가      1
천왕동        1
대청동4가      1
상수동        1
내수동        1
제기동        1
삼선동3가      1
봉래동4가      1
우이동        1
홍익동        1
범전동        1
중곡동        1
당주동        1
장위동        1
율현동        1
일광면        1
효창동        1
남대문로5가     1
지사동        1
회현동2가      1
서대신동2가     1
원효로3가      1
삼선동4가      1
양평동1가      1
Name: addr_dong, Length: 285, dtype: int64
N    1912
Y      21
Name: addr_san, dtype: int64
아파트     1656
주상복합     277
Name: Apartment_usage, dtype: int64
N    1854
Y      79
Name: Share_auction_YorN, dtype: int64
배당      1921
          12
Name: Close_result, dtype: int64

중요도

#### 1:         Minimum_sales_price 9.308153e-01 2.240703e-02 0.0173780589
#### 2:        Total_land_real_area 4.445213e-02 1.354885e-02 0.0164071658
#### 3:       Total_appraisal_price 1.415167e-02 3.105956e-02 0.0803761714
#### 4:               Auction_class 2.635033e-03 1.689808e-03 0.0256538296
####  5:                 Claim_price 1.177097e-03 2.968867e-02 0.1730785788
####  6:           Appraisal_company 6.404038e-04 4.100142e-02 0.0865366403
####  7:              Appraisal_date 5.062592e-04 2.003077e-02 0.0232100401
####  8:         Total_building_area 4.466385e-04 1.233611e-01 0.0295744892
####  9:        Preserve_regist_date 4.455002e-04 9.668331e-02 0.0401986821
#### 10:                 addr_bunji1 4.064291e-04 1.476911e-02 0.0115036922
#### 11:          First_auction_date 3.978370e-04 1.765984e-02 0.0375138250
#### 12:                    Specific 3.838895e-04 3.900765e-03 0.0011298387
#### 13:                    addr_etc 3.290080e-04 2.868382e-02 0.0257425743
#### 14:       Total_land_gross_area 3.199161e-04 1.562766e-02 0.0296486639
#### 15:                     point.y 2.799453e-04 6.156788e-02 0.0274260737
#### 16:          Final_auction_date 2.583567e-04 1.710037e-02 0.0101632504
#### 17:                     point.x 2.518635e-04 6.805171e-02 0.0521527203
#### 18:                   addr_dong 2.236558e-04 8.739885e-03 0.0096652207
#### 19:                   road_name 2.053876e-04 1.673823e-02 0.0120732475
#### 20:                 Total_floor 1.917382e-04 8.956056e-02 0.0196324382
#### 21: Total_building_auction_area 1.867941e-04 1.067616e-02 0.0178363522
#### 22:                    Creditor 1.826600e-04 3.244717e-02 0.0568826782
#### 23:               Current_floor 1.667525e-04 1.082847e-01 0.0390728170
#### 24:               Auction_count 1.524420e-04 3.543777e-03 0.0057352892
#### 25:                     addr_si 1.448513e-04 4.238207e-03 0.0061564952
#### 26:                 road_bunji1 1.407169e-04 2.488153e-02 0.0260843074
#### 27:                  Close_date 1.179360e-04 1.335238e-02 0.0069128117
#### 28:                 addr_bunji2 1.175341e-04 4.482512e-02 0.0366965794
#### 29:                   Bid_class 7.699822e-05 2.586166e-03 0.0513805093
#### 30:   Auction_miscarriage_count 7.650626e-05 1.017814e-02 0.0025351833
#### 31:     Total_land_auction_area 4.006386e-05 1.286578e-02 0.0181953045
#### 32:                 road_bunji2 2.602869e-05 6.314193e-03 0.0019060234
#### 33:             Apartment_usage 1.926514e-05 3.139982e-04 0.0006543263
#### 34:          Share_auction_YorN 1.679568e-05 7.377890e-04 0.0002331203
#### 35:                     addr_do 9.588449e-06 7.046316e-06 0.0001311302
#### 36:                     addr_li 6.883177e-06 2.308679e-03 0.0004066360
#### 37:                    addr_san 1.556274e-07 5.687875e-04 0.0001152356

In [14]:
train1.columns

Index(['Auction_key', 'Claim_price', 'Auction_count',
       'Auction_miscarriage_count', 'Total_land_gross_area',
       'Total_land_real_area', 'Total_land_auction_area',
       'Total_building_area', 'Total_building_auction_area',
       'Total_appraisal_price',
       ...
       'addr_dong_휘경동', 'addr_dong_흑석동', 'addr_san_N', 'addr_san_Y',
       'Apartment_usage_아파트', 'Apartment_usage_주상복합', 'Share_auction_YorN_N',
       'Share_auction_YorN_Y', 'Close_result_    ', 'Close_result_배당'],
      dtype='object', length=1042)

In [7]:
train = train1[["Minimum_sales_price","Total_land_real_area","Total_appraisal_price","Claim_price"]]
test = test_df[["Minimum_sales_price","Total_land_real_area","Total_appraisal_price","Claim_price"]]
y_train = train_df.Hammer_price.values

## (나) 예측 모델을 위한 기본 머신 러닝 기법 이외의 앙상블 모형을포함한 머신 러닝 기법을 적용
## (가) 모델 성능 평가

# 머신러닝 + 모델평가

In [8]:
#classifiaction.
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC,SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB

#regression
from sklearn.linear_model import LinearRegression,Ridge,Lasso,RidgeCV
from sklearn.ensemble import RandomForestRegressor,BaggingRegressor,GradientBoostingRegressor,AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor

#model selection
from sklearn.model_selection import train_test_split,cross_validate
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV

#evaluation metrics
from sklearn.metrics import mean_squared_log_error,mean_squared_error, r2_score,mean_absolute_error # for regression
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score  # for classification

# 샘플링 8:2

In [39]:
x_train,x_test,y_train,y_test=train_test_split(train1[["Minimum_sales_price","Total_land_real_area","Total_appraisal_price","Claim_price"]],train1["a"],test_size=0.30,random_state=42)

(가) 위에서 수행한 모델에 대한 모델 성능 평가.

In [40]:
models=[RandomForestRegressor(),AdaBoostRegressor(),BaggingRegressor(),SVR(),KNeighborsRegressor()]
model_names=['RandomForestRegressor','AdaBoostRegressor','BaggingRegressor','SVR','KNeighborsRegressor']
rmsle=[]
d={}
for model in range (len(models)):
    clf=models[model]
    clf.fit(x_train,y_train)
    test_pred=clf.predict(x_test)
    rmsle.append(np.sqrt(mean_squared_error(test_pred,y_test)))
d={'Modelling Algo':model_names,'RMSLE':rmsle}   
d

{'Modelling Algo': ['RandomForestRegressor',
  'AdaBoostRegressor',
  'BaggingRegressor',
  'SVR',
  'KNeighborsRegressor'],
 'RMSLE': [49447446.19341551,
  59703045.35344885,
  52687295.17494417,
  77339237.62113033,
  58192322.51505825]}

In [41]:
no_of_test=[2500]
params_dict={'n_estimators':no_of_test,'n_jobs':[-1],'max_features':["auto",'sqrt','log2']}
clf_rf=GridSearchCV(estimator=RandomForestRegressor(),param_grid=params_dict,scoring='neg_mean_squared_error')
clf_rf.fit(x_train,y_train)
pred=clf_rf.predict(x_test)
print((np.sqrt(mean_squared_error(pred,y_test))))

49630938.8855412

In [42]:
# for KNN
n_neighbors=[]
for i in range (0,50,5):
    if(i!=0):
        n_neighbors.append(i)
params_dict={'n_neighbors':n_neighbors,'n_jobs':[-1]}
clf_knn=GridSearchCV(estimator=KNeighborsRegressor(),param_grid=params_dict,scoring='neg_mean_squared_error')
clf_knn.fit(x_train,y_train)
pred=clf_knn.predict(x_test)
print((np.sqrt(mean_squared_error(pred,y_test))))

53597363.23851422

# 머신러닝2

In [43]:
from sklearn.linear_model import ElasticNet, Lasso,  BayesianRidge, LassoLarsIC
from sklearn.ensemble import RandomForestRegressor,  GradientBoostingRegressor
from sklearn.kernel_ridge import KernelRidge
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import RobustScaler
from sklearn.base import BaseEstimator, TransformerMixin, RegressorMixin, clone
from sklearn.model_selection import KFold, cross_val_score, train_test_split
from sklearn.metrics import mean_squared_error
import xgboost as xgb
import lightgbm as lgb

In [44]:
train = train1[["Minimum_sales_price","Total_land_real_area","Total_appraisal_price","Claim_price"]]
test = test_df[["Minimum_sales_price","Total_land_real_area","Total_appraisal_price","Claim_price"]]
y_train = train1.a.values

In [45]:
'''
train = train_df[["Minimum_sales_price","Total_appraisal_price","Total_land_real_area","Auction_count"]]
test  = test_df[["Minimum_sales_price","Total_appraisal_price","Total_land_real_area","Auction_count"]]
ntrain = train.shape[0]
ntest = test.shape[0]
y_train = train_df.Hammer_price.values
y_test = test_df.Hammer_price.values
'''
#Validation function
n_folds = 5

def rmsle_cv(model):
    kf = KFold(n_folds, shuffle=True, random_state=42).get_n_splits(train.values)
    rmse= np.sqrt(-cross_val_score(model, train.values, y_train, scoring="neg_mean_squared_error", cv = kf))
    #rmse=np.sqrt(mean_squared_error(model, train.values, y_train))
    return(rmse)

In [46]:
lasso = make_pipeline(RobustScaler(), Lasso(alpha =0.0005, random_state=1))

In [47]:
ENet = make_pipeline(RobustScaler(), ElasticNet(alpha=0.0005, l1_ratio=.9, random_state=3))

In [48]:
KRR = KernelRidge(alpha=0.6, kernel='polynomial', degree=2, coef0=2.5)

In [49]:
GBoost = GradientBoostingRegressor(n_estimators=3000, learning_rate=0.05,
                                   max_depth=4, max_features='sqrt',
                                   min_samples_leaf=15, min_samples_split=10, 
                                   loss='huber', random_state =5)

In [50]:
model_xgb = xgb.XGBRegressor(colsample_bytree=0.4603, gamma=0.0468, 
                             learning_rate=0.05, max_depth=3, 
                             min_child_weight=1.7817, n_estimators=2200,
                             reg_alpha=0.4640, reg_lambda=0.8571,
                             subsample=0.5213, silent=1,
                             random_state =7, nthread = -1)

In [51]:
model_lgb = lgb.LGBMRegressor(objective='regression',num_leaves=5,
                              learning_rate=0.05, n_estimators=720,
                              max_bin = 55, bagging_fraction = 0.8,
                              bagging_freq = 5, feature_fraction = 0.2319,
                              feature_fraction_seed=9, bagging_seed=9,
                              min_data_in_leaf =6, min_sum_hessian_in_leaf = 11)

In [52]:
score = rmsle_cv(lasso)
print("\nLasso score: {:.4f} ({:.4f})\n".format(score.mean(), score.std()))

Lasso score: 75450866.2243 (59924450.8369)

In [53]:
score = rmsle_cv(ENet)
print("ElasticNet score: {:.4f} ({:.4f})\n".format(score.mean(), score.std()))

ElasticNet score: 75423070.5310 (59871055.6012)

In [54]:
score = rmsle_cv(KRR)
print("Kernel Ridge score: {:.4f} ({:.4f})\n".format(score.mean(), score.std()))

C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "

Kernel Ridge score: 499031357.5658 (875700905.3467)

In [55]:
score = rmsle_cv(GBoost)
print("Gradient Boosting score: {:.4f} ({:.4f})\n".format(score.mean(), score.std()))

Gradient Boosting score: 52110086.0089 (22390027.2949)

In [56]:
score = rmsle_cv(model_xgb)
print("Xgboost score: {:.4f} ({:.4f})\n".format(score.mean(), score.std()))

Xgboost score: 59178721.6842 (22554141.2652)

In [57]:
score = rmsle_cv(model_lgb)
print("LGBM score: {:.4f} ({:.4f})\n" .format(score.mean(), score.std()))

LGBM score: 54449136.7672 (22567819.8209)

## (나) 선정한 평가 메트릭(정확도, F-measure, MSE 등)을 계산해보고 이에 대한 의미 찾기

각각의 모델의 RMSE를 확인 한다.

모델마다 많은 차이가 난다 

랜덤포래스트 모델이 가장 낮은 수치를 보여준다.

## (다) 모델 성능 평가 기준으로 다양한 방법을 통해 모델 성능 개선

# 스태킹 + 앙상블 기법 사용

In [58]:
class AveragingModels(BaseEstimator, RegressorMixin, TransformerMixin):
    def __init__(self, models):
        self.models = models
        
    # we define clones of the original models to fit the data in
    def fit(self, X, y):
        self.models_ = [clone(x) for x in self.models]
        
        # Train cloned base models
        for model in self.models_:
            model.fit(X, y)

        return self
    
    #Now we do the predictions for cloned models and average them
    def predict(self, X):
        predictions = np.column_stack([
            model.predict(X) for model in self.models_
        ])
        return np.mean(predictions, axis=1)

In [59]:
averaged_models = AveragingModels(models = (ENet, GBoost, KRR, lasso))

score = rmsle_cv(averaged_models)
print(" Averaged base models score: {:.4f} ({:.4f})\n".format(score.mean(), score.std()))

C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "

 Averaged base models score: 164404475.5208 (241778736.6570)

In [60]:
def rmsle(y_test, y_pred):
    return np.sqrt(mean_squared_error(y_test, y_pred))

In [62]:
class StackingAveragedModels(BaseEstimator, RegressorMixin, TransformerMixin):
    def __init__(self, base_models, meta_model, n_folds=5):
        self.base_models = base_models
        self.meta_model = meta_model
        self.n_folds = n_folds
   
    # We again fit the data on clones of the original models
    def fit(self, X, y):
        self.base_models_ = [list() for x in self.base_models]
        self.meta_model_ = clone(self.meta_model)
        kfold = KFold(n_splits=self.n_folds, shuffle=True, random_state=156)
        
        # Train cloned base models then create out-of-fold predictions
        # that are needed to train the cloned meta-model
        out_of_fold_predictions = np.zeros((X.shape[0], len(self.base_models)))
        for i, model in enumerate(self.base_models):
            for train_index, holdout_index in kfold.split(X, y):
                instance = clone(model)
                self.base_models_[i].append(instance)
                instance.fit(X[train_index], y[train_index])
                y_pred = instance.predict(X[holdout_index])
                out_of_fold_predictions[holdout_index, i] = y_pred
                
        # Now train the cloned  meta-model using the out-of-fold predictions as new feature
        self.meta_model_.fit(out_of_fold_predictions, y)
        return self
   
    #Do the predictions of all base models on the test data and use the averaged predictions as 
    #meta-features for the final prediction which is done by the meta-model
    def predict(self, X):
        meta_features = np.column_stack([
            np.column_stack([model.predict(X) for model in base_models]).mean(axis=1)
            for base_models in self.base_models_ ])
        return self.meta_model_.predict(meta_features)

In [63]:
stacked_averaged_models = StackingAveragedModels(base_models = (ENet, GBoost, KRR),
                                                 meta_model = lasso)

score = rmsle_cv(stacked_averaged_models)
print("Stacking Averaged models score: {:.4f} ({:.4f})".format(score.mean(), score.std()))

C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "

C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "

Stacking Averaged models score: 80774955.5982 (79350800.5939)

In [64]:
stacked_averaged_models.fit(train.values, y_train)
stacked_train_pred = stacked_averaged_models.predict(train.values)
#stacked_pred = np.expm1(stacked_averaged_models.predict(test.values))
print(rmsle(y_train, stacked_train_pred))

C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "
C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "

40943407.57215471

In [65]:
ENet.fit(train, y_train)
ENet_train_pred = ENet.predict(train)
#ENet_pred = np.expm1(ENet.predict(test))
print(rmsle(y_train, ENet_train_pred))

56543808.84008945

In [66]:
model_xgb.fit(train, y_train)
xgb_train_pred = model_xgb.predict(train)
xgb_pred = model_xgb.predict(test)
print(rmsle(y_train, xgb_train_pred))

24478147.48972602

In [67]:
model_lgb.fit(train, y_train)
lgb_train_pred = model_lgb.predict(train)
#lgb_pred = np.expm1(model_lgb.predict(test.values))
print(rmsle(y_train, lgb_train_pred))

52253256.33626541

In [68]:
averaged_models.fit(train, y_train)
averaged_train_pred = averaged_models.predict(train)
#averaged_pred = np.expm1(averaged_models.predict(test.values))
print(rmsle(y_train, averaged_train_pred))

C:\Users\ktm\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:154: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn("Singular matrix in solving dual problem. Using "

49654777.48616814

In [69]:
print('RMSLE score on train data:')
print(rmsle(y_train,averaged_train_pred*0.50 +
               xgb_train_pred*0.10 + lgb_train_pred*0.40 ))

RMSLE score on train data:
45429944.5534277

In [ ]:
ensemble = averaged_pred*0.50 + xgb_pred*0.10 + lgb_pred*0.40

# 데이터 저장

In [74]:
sub = pd.DataFrame()
sub['Id'] = test_df.Auction_key
sub['SalePrice'] = ensemble + test.Minimum_sales_price
sub.to_csv('submission.csv',index=False)

실제 비지니스에서는 예측단계에서 끝나는 것이아닌 투자를 하기 때문에 

사용하기 위해서는 그 데이터에 맞는 중요변수를 확실하게 찾고 오차를 더 줄여야 한다.